### ISSUE TITLE
TransientExceptionRetryPolicyTests Fail Intermittently

### ISSUE THREAD

**Issue by thefringeninja** [damianh/Cedar#26]
Cedar.Handlers.TransientExceptionRetryPolicyTests.When_transient_exception_thrown_once_then_should_retry [FAIL]
799   Cedar.Handlers.TransientException : Exception of type 'Cedar.Handlers.TransientException' was thrown.
800   Stack Trace:
801      c:\projects\cedar\src\Cedar.Tests\Handlers\TransientExceptionRetryPolicyTests.cs(43,0): at Cedar.Handlers.TransientExceptionRetryPolicyTests.<>c__DisplayClass5.<When_transient_exception_thrown_once_then_should_retry>b__4()
802      c:\projects\cedar\src\Cedar\Handlers\TransientExceptionRetryPolicy.cs(64,0): at Cedar.Handlers.TransientExceptionRetryPolicy.<Retry>d__0.MoveNext()
803   --- End of stack trace from previous location where exception was thrown ---
804      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
805      c:\projects\cedar\src\Cedar\Handlers\TransientExceptionRetryPolicy.cs(59,0): at Cedar.Handlers.TransientExceptionRetryPolicy.<Retry>d__0.MoveNext()
806   --- End of stack trace from previous location where exception was thrown ---
807      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
808      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
809      c:\projects\cedar\src\Cedar.Tests\Handlers\TransientExceptionRetryPolicyTests.cs(35,0): at Cedar.Handlers.TransientExceptionRetryPolicyTests.<When_transient_exception_thrown_once_then_should_retry>d__7.MoveNext()

**Comment by thefringeninja** [comment]
Looked over the actual code, seems pretty straightforward to me. The code has not changed and this test fails rarely if ever.

**Comment by damianh** [comment]
Maybe we should apply a transient retry policy to the test :trollface:

**Comment by damianh** [comment]
Functionality pulled because of #44
